apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-back-despachos
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-despachos
  template:
    metadata:
      labels:
        app: back-despachos
    spec:
      containers:
      - name: back-despachos
        image: 495256692270.dkr.ecr.us-east-1.amazonaws.com/innovatech-back-despachos-ev3:latest
        ports:
        - containerPort: 8082
        # 👇 VARIABLES DE ENTORNO INYECTADAS PARA EVITAR EL CRASH 👇
        env:
        - name: DB_ENDPOINT
          value: "TU_ENDPOINT_DE_AWS_RDS_AQUÍ.amazonaws.com"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "innovatech_despachos"  # O el nombre que le diste a la BD de despachos
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "TU_CONTRASEÑA_RDS"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: back-despachos-service
  namespace: default
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: back-despachos
  type: ClusterIP